// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:riverpod_http_request/firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';

// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
//  );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP2q3gsNvH4IiQOZ7DJXvQdxORRyG373s',
    appId: '1:379702735793:web:1a231cd6549881067a8390',
    messagingSenderId: '379702735793',
    projectId: 'flutter1-a79c2',
    authDomain: 'flutter1-a79c2.firebaseapp.com',
    storageBucket: 'flutter1-a79c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3AY4bPo3kkrbxKVZgEG71dsywTaVXaqU',
    appId: '1:379702735793:android:4cebe33539a2ab187a8390',
    messagingSenderId: '379702735793',
    projectId: 'flutter1-a79c2',
    storageBucket: 'flutter1-a79c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrGW_pZzWZqCRSlgTEPdu_SqbBXKpgjpA',
    appId: '1:379702735793:ios:8fc926b17333f2e57a8390',
    messagingSenderId: '379702735793',
    projectId: 'flutter1-a79c2',
    storageBucket: 'flutter1-a79c2.appspot.com',
    iosClientId: '379702735793-sv0tsc33b55g7qnomll3tnop4livhhja.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodHttpRequest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrGW_pZzWZqCRSlgTEPdu_SqbBXKpgjpA',
    appId: '1:379702735793:ios:9b64579391289c067a8390',
    messagingSenderId: '379702735793',
    projectId: 'flutter1-a79c2',
    storageBucket: 'flutter1-a79c2.appspot.com',
    iosClientId: '379702735793-2kspnsu2e4ejfa4urdgm47tkere65l20.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodHttpRequest.RunnerTests',
  );
}
